name: Build and Test

on:
  push:
    branches:
      - main
    paths:
      - '**.tsx?'
      - '**.jsx?'
  pull_request:
    branches:
      - main
      - v3.x

jobs:
  test:
    name: Running vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Test with Coverage
        run: pnpm run coverage

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
