name: Lint Check

on:
  push:
    branches:
      - main
    paths:
      - '**.tsx?'
      - '**.jsx?'
  pull_request:
    branches:
      - main
      - v3.x
    paths:
      - '**.tsx?'
      - '**.jsx?'
jobs:
  lint-check:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint:ci
